### ISSUE TITLE
"mongoose" is imported by "" but could not be resolved – treating it as an external dependency.

### ISSUE THREAD

**Issue by kantar0** [kwameopareasiedu/docts#3]
Hello, I have been testing this library and everything works fine for functions that do not need imports, it has worked for me with fetch and everything is fine, but now that I want to implement moongose, I get this observation:
`"mongoose" is imported by "src/utils/getbnbpricefromusd/index.ts", but could not be resolved – treating it as an external dependency.`

my index.ts :

```javascript

import { DoFunction } from "../../../types/global"
import { Schema, connect, model } from 'mongoose'
import { IRate } from "../../../types/global"

const rateSchema = new Schema<IRate>(
  {
    last_updated: {
      type: Date,
      required: true
    },
    bnb_price: {
      type: Number,
      required: true
    }
  },
  {
    versionKey: false,
    timestamps: true
  }
)
const Rate = model<IRate>('Rate', rateSchema)

const CMC_PRO_API_KEY = ""
export const main: DoFunction = async () => {
  try {
    await connect(`mongodb+srv://user:password@db-mongodb-aaaa-00000-00000000mongo.ondigitalocean.com/database`, {
      tls: true,
    authSource: 'admin',
    replicaSet: ''
    })
    const response = await fetch(`https://pro-api.coinmarketcap.com/v2/tools/price-conversion?amount=1&symbol=USD&convert=BNB`, {
      headers: { 
        "X-CMC_PRO_API_KEY": CMC_PRO_API_KEY
      }
    }).then(res => res.json())
    const rate = new Rate({
      last_updated: response.data.quote.BNB.last_updated,
      bnb_price: response.data.quote.BNB.price
    })
    await rate.save()
    if (rate.save() === null) {
      throw new Error("Error saving rate")
    }
    console.log("Success")
    return {
      body: "Success"
    }
    
  } catch (error) {
    return {
      body: error
    }
  }
};

```

my interface is: 
`export interface IRate {
  last_updated: Date,
  bnb_price: number,
}`

**Comment by kwameopareasiedu** [comment]
Hi @kantar0 Thanks for check out the project.

What you are seeing is just a warning from Rollup which you can ignore. If you check the generated `packages/<package name>/<function-name>` directory, you'll see that a `package.json` was also generated. In the `package.json`, you'll see **mongoose** under the `dependencies`. 

When deployed DigitalOcean functions installs dependencies specified in the `package.json` so Mongoose will work in the deployed function.

**Comment by kwameopareasiedu** [comment]
I'm closing this issues because this isn't an error with the library. Feel free to reopen if you have build issues concerning this.
