### ISSUE TITLE
Type `DoFunctionArgs` contains deprecated fields

### ISSUE THREAD

**Issue by maximilliangeorge** [kwameopareasiedu/docts#7]
The following type does not seem to be up to date according to type DigitalOcean [documentation](https://docs.digitalocean.com/products/functions/reference/parameters-responses/#parsed-web-events).

```typescript
interface DoFunctionArgs {
    __ow_headers?: Record<string, any>
    __ow_path?: string
    __ow_method?: 'get' | 'post' | 'put' | 'patch' | 'delete' | 'options'
    __ow_body?: string | Record<string, any>
    __ow_query?: string

    [k: string]: any
  }
  ```
  
  > Additional legacy keys such as __ow_headers, __ow_method, and __ow_path may be available in the event parameter. These keys are deprecated and should not be used. All of the data they contain is also provided under the http key, which should be used instead.
  
 The new web event has the following format:
 
 ```js
{
  "http": {
      "headers": {
        "accept": String,
        "accept-encoding": String,
        "content-type": String,
        "user-agent": String,
        "x-forwarded-for": String,
        "x-forwarded-proto": String,
        "x-request-id": String
      },
      "method": String,
      "path": String
    },
    [String]: any
  }
  ```

**Comment by kwameopareasiedu** [comment]
@maximilliangeorge Just published the latest update which adds the `http` field and deprecates the __ow_* fields
https://github.com/kwameopareasiedu/docts/releases/tag/1.2.0
https://www.npmjs.com/package/docts-cli
